### ISSUE TITLE
Update version on hex.pm

### ISSUE THREAD

**Issue by nickvanbaelen** [onboardingsystems/enum_type#11]
First off, thanks for the library!

I am using it in my project and was loading it as a hex.pm dependency together with Elixir version 1.10.3

When compiling I noticed warnings from a deprecated function being used (Code.ensure_compiled?...) and started looking into it. Looking through your GitHub releases, I can see you guys already fixed this, thanks for that!

But it seems you haven't updated the hex.pm version yet. It is still sitting at version 1.0.1 whereas on GitHub you already pushed out version 1.1.1 and 1.1.2 of the library.

As a workaround I'm currently loading the new version of the library as a GitHub dependency in my project, but I prefer to use it as a hex.pm dependency since it's also on there.

Could you guys update it?

**Comment by brettv** [comment]
For now, doing it as a GitHub dependency is the right way.  We don't have control of the hex.pm account that originally published this library so we cannot publish a new version.  Let me try reaching out the account owner again.

**Comment by nickvanbaelen** [comment]
When you get in touch, maybe it'll be useful transferring or adding
yourself as an owner for the package (
https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html)

This way you also have rights to publish / revert releases for the package!

**Comment by cadebward** [comment]
@nickvanbaelen We finally got ownership transferred over and have published a new version: v1.1.2

**Comment by nickvanbaelen** [comment]
Awesome, thanks for the update

**Comment by nickvanbaelen** [comment]
I gave this a try yesterday and loaded the enum_type as a Hex dependency in my project. In contrast to the GitHub version (1.1.2), my project does not compile with the Hex.pm version (also 1.1.2).

The compilation error that I get is due to the fact that you changed `@behaviour Ecto.Type` by `use Ecto.Type`. I'm simply using the `defenum` macro on line 4 in my types.ex file.

`** (CompileError) lib/racket/gateway/interface/types.ex:4: module Ecto.Type is not loaded and could not be found
    (elixir 1.10.3) expanding macro: Kernel.use/1`

When looking at the versioning, your tagging is off. If you look at your `master` branch, it contains changes apparently for version 1.1.2, but you didn't tag your latest commit on master with 1.1.2 but 3 commits earlier. This explains why fetching version 1.1.2 as a GitHub dependency in my project (which still contains `@behaviour Ecto.Type`) doesn't exhibit the compilation error. Whereas on Hex.pm you probably uploaded your latest version (as reflected on `master`) to the repository.

Anyway, housekeeping aside, why am I unable to compile using enum_type version 1.1.2?

**Comment by cadebward** [comment]
Yeah this change assumed `Ecto` was loaded as a dependency. Ideally, we'd break out the ecto dependent code into another package. If you bring in Ecto, it should work. If that doesn't sound reasonable, we could probably just copy in the default implementations.

**Comment by cadebward** [comment]
It looks like `use Ecto.Type` was introduced in [Ecto 3.2.0](https://github.com/elixir-ecto/ecto/blob/v3.4.6/CHANGELOG.md#v320-2019-09-07). Are you using 3.2 or later?

**Comment by nickvanbaelen** [comment]
Not using Ecto in my application. Since it is a dependency that EnumType is using, shouldn't this get compiled into your binary? (and eventually into mine if I set a dependency towards EnumType)

**Comment by cadebward** [comment]
That would be ideal. With `ParameterizedType` and `Ecto.Enum` coming out soon, we're going to wait and see where that leaves this library before making any decisions.
